INSERT INTO cli_regions (id,name) VALUES (1,'SouthAmerica');
INSERT INTO cli_regions (id,name) VALUES (2,'CentralAmerica');
INSERT INTO cli_regions (id,name) VALUES (3,'NorthAmerica');
INSERT INTO cli_regions (id,name) VALUES (4,'Europe');
INSERT INTO cli_regions (id,name) VALUES (5,'Asia');
INSERT INTO cli_regions (id,name) VALUES (6,'Africa');
INSERT INTO cli_regions (id,name) VALUES (7,'Oceania');
INSERT INTO cli_regions (id,name) VALUES (8,'Antartica');

INSERT INTO clients (name, surname, email, created_date, region_id) VALUES('Lean','Toloza','leandro@email.com','2010-01-01',1);
INSERT INTO clients (name, surname, email, created_date, region_id) VALUES('Lucas','Toledo','lucas@email.com','2010-01-02',2);
INSERT INTO clients (name, surname, email, created_date, region_id) VALUES('Pedro','Toloza','pedro@email.com','2010-01-03',3);
INSERT INTO clients (name, surname, email, created_date, region_id) VALUES('Juan','Toloza','juan@email.com','2010-01-04',4);
INSERT INTO clients (name, surname, email, created_date, region_id) VALUES('Carlos','Toloza','carlos@email.com','2010-01-05',5);
INSERT INTO clients (name, surname, email, created_date, region_id) VALUES('Lautaro','Toloza','lautaro@email.com','2010-01-11',6);
INSERT INTO clients (name, surname, email, created_date, region_id) VALUES('Facundo','Toloza','facundo@email.com','2010-01-06',7);
INSERT INTO clients (name, surname, email, created_date, region_id) VALUES('Martin','Toloza','martin@email.com','2010-01-07',8);
INSERT INTO clients (name, surname, email, created_date, region_id) VALUES('Pepe','Toloza','pepe@email.com','2010-01-08',1);
INSERT INTO clients (name, surname, email, created_date, region_id) VALUES('Nico','Toloza','nico@email.com','2010-01-09',2);
INSERT INTO clients (name, surname, email, created_date, region_id) VALUES('Manuel','Toloza','manuel@email.com','2010-01-22',3);
INSERT INTO clients (name, surname, email, created_date, region_id) VALUES('Augusto','Toloza','augusto@email.com','2010-01-23',4);
